openapi: "3.0.1"
info:
    version: 1.0
    title: SFG Brewery API
paths:
    /api/v1/beer:
        get:
            description: List Beers
            responses:
                '200':
                    description: List Beers Response
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/beer'
    /api/v1/beer/{beerId}:
        get:
            description: Get Beer by Id
            responses:
                '200':
                    description: List Beers Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/beer'
    /api/v1/customers/new:
        post:
            description: Register as new customer
            requestBody:
                required: false
                content:
                    application/json:
                        schema:
                        ## todo
            responses:
                '200':
                    description: HTTP Okay
                    content:
                        application/json:
                            schema:
                            ## todo
    /api/customers/{customerId}:
        get:
            description: Get customer by Id
            responses:
                '200':
                    description: HTTP Okay
                    content:
                        application/json:
                            schema:
                                ## todo
    /api/v1/customers/{customerId}/order:
        post:
            description: Place Order
            requestBody:
                required: false
                content:
                    application/json:
                        schema:
                           ## todo
            responses:
                '200':
                    description: HTTP Okay
                    content:
                        application/json:
                            schema:
                             ## todo
    /api/v1/customers/{customerId}/order/pickup:
        post:
            description: Pickup Order
            requestBody:
                required: false
                content:
                    application/json:
                        schema:
                        ## todo
            responses:
                '200':
                    description: HTTP Okay
                    content:
                        application/json:
                            schema:
                            ## todo
                ## todo add callback
components:
    schemas:
        beer:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                name:
                    type: string
                style:
                    type: string
                quanityOnHand:
                    type: integer
                price:
                    type: string
                    format: decimal

        beerOrder:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                customerId:
                    type: string
                beerOrderLines:
                    type: array
                    items:
                        $ref: '#/components/schemas/beerOrderLine'
                orderStatus:
                    type: string
                    enum:
                        - NEW
                        - READY
                        - PICKED_UP
        beerOrderLine:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                beerId:
                    type: string
                    format: uuid
        customer:
            type: object
            properties:
                id:
                    type: string
                    format: uuid

